name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Java (Amazon Corretto) and Gradle Build
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Make Gradle wrapper executable
      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      # Extract version from gradle.properties
      - name: Extract Version
        id: get-version
        run: |
          VERSION=$(grep '^version=' gradle.properties | cut -d '=' -f2 | tr -d '[:space:]')
          echo "Version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Set up QEMU for Multi-Arch Build (optional for arm64, but included for consistency)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to Docker Registry
      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: https://registry.tobi1craft.de
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            https://registry.tobi1craft.de/nowbot:latest
            https://registry.tobi1craft.de/nowbot:${{ env.VERSION }}
